### ISSUE TITLE
Create title properly

### ISSUE THREAD

**Issue by MrMaksimize** [opensandiego/open-dsd-notifications#2]

**Comment by cbaakel** [comment]
Basic title added, with proper URL link.

**Comment by ahempton** [comment]
Thanks Charles!  Not sure how I send you a direct message on this yet, but just wondered how the Open DSD app is progressing and what other info you might need?  I seem to recall we were stuck on Citygram.

**Comment by cbaakel** [comment]
Hi Alex - This is still in limbo. Nothing from Citygram. Maybe you or
someone else should try reaching out instead.

I also need to demote myself from this project, I'm moving from SD and have
too much going on to handle leading this project.

Charles Baakel
m: 617-388-8513

**Comment by ahempton** [comment]
Thanks for the update and all your help! Good luck with your move.
Alex
